language: generic

sudo: required
services:
  - docker

before_install:
  - docker build -t cristianahl/complex-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true cristianahl/complex-test npm run test -- --coverage

after_success:
  - docker build -t cristianahl/complex-client ./client
  - docker build -t cristianahl/complex-nginx ./nginx
  - docker build -t cristianahl/complex-server ./server
  - docker build -t cristianahl/complex-worker ./worker

  # log in to docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # push imgs to docker hub
  - docker push cristianahl/complex-client
  - docker push cristianahl/complex-nginx
  - docker push cristianahl/complex-server
  - docker push cristianahl/complex-worker  