language: generic

sudo: required
services:
  - docker

before_install:
  - docker build -t cristiana/complex-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true cristiana/complex-test npm run test -- --coverage

after_success:
  - docker build -t cristiana/complex-client ./client
  - docker build -t cristiana/complex-nginx ./nginx
  - docker build -t cristiana/complex-server ./server
  - docker build -t cristiana/complex-worker ./worker

  # log in to docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  
  # push imgs to docker hub
  - docker push cristiana/complex-client
  - docker push cristiana/complex-nginx
  - docker push cristiana/complex-server
  - docker push cristiana/complex-worker

  